In [2]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.replace({True:1,False:0})
dataset

C:\Users\PRIYANKA MANI\AppData\Local\Temp\ipykernel_4568\3350150185.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0})

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
dataset=dataset.drop("User ID",axis=1)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [6]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [8]:
dependent=dataset['Purchased']
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)
X_train, X_test, Y_train, Y_test

(     Age  EstimatedSalary  Gender_Male
 218   46            96000            0
 101   28            59000            1
 311   39            96000            1
 194   28            89000            1
 326   41            72000            1
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0

 [266 rows x 3 columns],
      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 168   29           148000            1
 150   26            15000            0
 393   60            42000            1
 66    24            19000            1
 240   42           149000            1

 [134 rows x 3 columns],
 218    0
 101    0
 311    1
 194    0
 326    0
       ..
 323    1
 192    0
 117    0
 47     0
 172    0
 Name: Purchased, Length: 266, dtype: int64,
 132    0
 309    0
 341    0
 196    0
 246    0
       ..
 168    1
 150    0
 393    1
 66     0
 240    1
 Name: Purchased, Length: 134, dtype: int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.87183164 0.88368976 0.8798608  0.89883662
        nan        nan 0.87545254 0.88686536 0.88335135 0.90274366]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [14]:
# print best parameter after tuning 
print(grid.best_params_) 
result=grid.cv_results_
print(result)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, grid_predictions)

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}
{'mean_fit_time': array([0.00212598, 0.00149317, 0.0333755 , 0.20554361, 0.02412357,
       0.20271773, 0.00267239, 0.00080628, 0.02202473, 0.19592695,
       0.02391992, 0.17714839]), 'std_fit_time': array([0.00124779, 0.00080008, 0.00656333, 0.01281013, 0.00346733,
       0.0118562 , 0.00132396, 0.0009875 , 0.00234282, 0.00361945,
       0.00185983, 0.01843404]), 'mean_score_time': array([0.        , 0.        , 0.01207333, 0.0108748 , 0.00454931,
       0.01057525, 0.        , 0.        , 0.00362692, 0.01108146,
       0.00630703, 0.01242952]), 'std_score_time': array([0.        , 0.        , 0.00427714, 0.00245689, 0.00117154,
       0.00301277, 0.        , 0.        , 0.00150949, 0.00073159,
       0.00297706, 0.0026751 ]), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                   'auto', 'sqrt', 'sqrt', 'log2', 'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_estimators': masked_array(data=[10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'params': [{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 10}, {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}, {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 10}, {'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100}, {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}], 'split0_test_score': array([       nan,        nan, 0.82626263, 0.84714126, 0.86747844,
       0.86747844,        nan,        nan, 0.86747844, 0.82626263,
       0.84714126, 0.86747844]), 'split1_test_score': array([       nan,        nan, 0.87004744, 0.85080904, 0.87004744,
       0.86875226,        nan,        nan, 0.86875226, 0.88810678,
       0.8890223 , 0.90717674]), 'split2_test_score': array([       nan,        nan, 0.8515274 , 0.8515274 , 0.85054317,
       0.8515274 ,        nan,        nan, 0.83248257, 0.8515274 ,
       0.83248257, 0.8515274 ]), 'split3_test_score': array([       nan,        nan, 0.88679245, 0.92527158, 0.90616583,
       0.94416086,        nan,        nan, 0.92527158, 0.90616583,
       0.90506914, 0.92527158]), 'split4_test_score': array([       nan,        nan, 0.9245283 , 0.9436995 , 0.90506914,
       0.96226415,        nan,        nan, 0.88327784, 0.96226415,
       0.94304148, 0.96226415]), 'mean_test_score': array([       nan,        nan, 0.87183164, 0.88368976, 0.8798608 ,
       0.89883662,        nan,        nan, 0.87545254, 0.88686536,
       0.88335135, 0.90274366]), 'std_test_score': array([       nan,        nan, 0.03314436, 0.0419084 , 0.02207516,
       0.045175  ,        nan,        nan, 0.02999357, 0.04686254,
       0.03991375, 0.03984116]), 'rank_test_score': array([9, 9, 8, 4, 6, 2, 9, 9, 7, 3, 5, 1])}

In [15]:

from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9180821729616219

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 5 44]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.94      0.93      0.93        85
           1       0.88      0.90      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.91      0.91       134
weighted avg       0.92      0.92      0.92       134

In [18]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

0.9667466986794718

In [19]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002126,0.001248,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.001493,0.000800,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.033376,0.006563,0.012073,0.004277,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.826263,0.870047,0.851527,0.886792,0.924528,0.871832,0.033144,8
3,0.205544,0.012810,0.010875,0.002457,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.847141,0.850809,0.851527,0.925272,0.943699,0.883690,0.041908,4
4,0.024124,0.003467,0.004549,0.001172,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.867478,0.870047,0.850543,0.906166,0.905069,0.879861,0.022075,6
5,0.202718,0.011856,0.010575,0.003013,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.867478,0.868752,0.851527,0.944161,0.962264,0.898837,0.045175,2
6,0.002672,0.001324,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000806,0.000987,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.022025,0.002343,0.003627,0.001509,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.867478,0.868752,0.832483,0.925272,0.883278,0.875453,0.029994,7
9,0.195927,0.003619,0.011081,0.000732,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.826263,0.888107,0.851527,0.906166,0.962264,0.886865,0.046863,3
10,0.023920,0.001860,0.006307,0.002977,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.847141,0.889022,0.832483,0.905069,0.943041,0.883351,0.039914,5
11,0.177148,0.018434,0.012430,0.002675,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.867478,0.907177,0.851527,0.925272,0.962264,0.902744,0.039841,1

In [20]:
import pickle
filename="finalized_model_RF.sav"
pickle.dump(grid, open(filename,'wb'))

In [21]:
age_input=float(input("Age:"))
salary_input=float(input("saalry:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 27
saalry: 50000
Sex Male 0 or 1: 0

In [22]:
loaded_model=pickle.load(open("finalized_model_RF.sav",'rb'))
result=loaded_model.predict([[age_input,salary_input,sex_male_input]])
result
#Future_Prediction=grid.predict([[age_input,salary_input,sex_male_input]])
#print("Future_Prediction={}".format(Future_Prediction))

array([1], dtype=int64)